---
name: Linting the Dockerfile

on:  # yamllint disable-line rule:truthy
  push:
    tags-ignore:
      - "**"
    branches:
      - "**"
    paths:
      - "Dockerfile"
      - "hadolint.yaml"
      - ".github/workflows/*.yaml"

jobs:
  lint:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: "Dockerfile"
          config: ".hadolint.yaml"

      - name: Lint YAML files
        uses: ibiqlik/action-yamllint@v3
        with:
          config_data: "{extends: default, rules: {document-start: disable, line-length: disable}}"
