---
name: Publish  # Push latest version of the container to docker hub

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - "**"

env:
  ORGANIZATION: "derekstraka"
  IMAGE_NAME: "terraform-azure"
  IMAGE_TAG: "latest"

jobs:
  build_push_latest:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Retrieve latest suported versions
        run: |
          SUPPORTED_VERSIONS=$(cat ./supported_versions.yaml | python3 -c 'import sys, yaml, json; print(json.dumps(yaml.safe_load(sys.stdin)))')
          echo "AZURE_CLI_VERSION=$(echo ${SUPPORTED_VERSIONS} | jq -r '.azure_cli_version | sort | .[-1]')" >> $GITHUB_ENV
          echo "TERRAFORM_VERSION=$(echo ${SUPPORTED_VERSIONS} | jq -r '.terraform_version | sort | .[-1]')" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          tags: ${{ env.ORGANIZATION }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG}}
          build-args: |
              TERRAFORM_VERSION=${{ env.TERRAFORM_VERSION }}
              AZURE_CLI_VERSION=${{ env.AZURE_CLI_VERSION }}

      - name: Generate the tests from the templates
        run: ./generate_tests.sh -t ${{ env.TERRAFORM_VERSION }} -a ${{ env.AZURE_CLI_VERSION  }}

      - name: run structure tests
        uses: plexsystems/container-structure-test-action@v0.1.0
        with:
          image: ${{ env.ORGANIZATION }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG}}
          config: tests/test.yaml

      - name: Build and push Docker image
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: ./Dockerfile
          push: ${{ github.event.base_ref =='refs/heads/main' }}
          tags: ${{ env.ORGANIZATION }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG}}
          build-args: |
                TERRAFORM_VERSION=${{ env.TERRAFORM_VERSION }}
                AZURE_CLI_VERSION=${{ env.AZURE_CLI_VERSION }}
